name: Continuous Test - User Information
 
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [14.x]
       
    steps:
      - uses: actions/checkout@v2
 
      - name: Use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v1
       
      - name: Install newman
        run: |
          npm install -g newman
 
      - name: Run Postman Collection  
        run: |
          make test
